language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 ./
  - python manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: us-east-1
  app: swe2_app2
  env: django-env02
  bucket_name: elasticbeanstalk-us-east-1-991023061782
  on:
    repo: emoltz/swe2_app
    branch: master
